version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      eslint:
        patterns:
          - "eslint*"
      test-tooling:
        patterns:
          - "jest*"
      extension-tooling:
        patterns:
          - "web-ext"
          - "addons-linter"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
